import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DAYS_OF_WEEK, MEAL_TYPES, DayOfWeek, MealType, Recipe, WeeklyMealSlot } from '@/types/models';

interface GeneratePdfOptions {
  weekLabel: string;
  householdName: string;
  slots: WeeklyMealSlot[];
  recipes: Recipe[];
}

export function generateWeeklyPlanPdf({ weekLabel, householdName, slots, recipes }: GeneratePdfOptions) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const getRecipeTitle = (day: DayOfWeek, meal: MealType): string => {
    const slot = slots.find(s => s.dayOfWeek === day && s.mealType === meal);
    if (!slot?.recipeId) return '—';
    const recipe = recipes.find(r => r.id === slot.recipeId);
    return recipe?.title ?? '—';
  };

  // Title
  doc.setFontSize(20);
  doc.text(`🍽️ ${householdName} — Meal Plan`, 148, 16, { align: 'center' });
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(weekLabel, 148, 24, { align: 'center' });
  doc.setTextColor(0);

  // Table
  const head = [['Day', '🌅 Breakfast', '☀️ Lunch', '🌙 Dinner']];
  const body = DAYS_OF_WEEK.map(day => [
    day,
    ...MEAL_TYPES.map(meal => getRecipeTitle(day, meal)),
  ]);

  autoTable(doc, {
    startY: 30,
    head,
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [255, 183, 77],
      textColor: [50, 50, 50],
      fontStyle: 'bold',
      fontSize: 11,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 10,
      cellPadding: 6,
      valign: 'middle',
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 30 },
      1: { cellWidth: 70, halign: 'center' },
      2: { cellWidth: 70, halign: 'center' },
      3: { cellWidth: 70, halign: 'center' },
    },
    alternateRowStyles: { fillColor: [255, 248, 240] },
    margin: { left: 20, right: 20 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Family Meal Planner', 148, pageHeight - 8, { align: 'center' });

  doc.save(`meal-plan-${weekLabel.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`);
}
